:sparkles: Create abstracts to simplify component creation
epitech-mirroring/Stellar-Forge pull request #16
Opened 2024-10-02 14:40 UTC by Marius-P1

This pull request introduces new classes and refactors existing interfaces to improve the structure and functionality of the `StellarForge` project. The changes include the addition of `AField`, `AFieldGroup`, and `AMeta` classes, as well as the removal of deleted constructors and operators from the `IComponent` interface.

### New Classes:

* `src/common/AField.cpp` and `src/common/AField.hpp`: Added `AField` class to represent individual fields with attributes such as name, description, and type. [[1]](diffhunk://#diff-0831262199525f0584640bded62d2a83c8b60e917edc71ea452bd094496dbe3eR1-R29) [[2]](diffhunk://#diff-1bb357630a1c2b1123b268be59720073f293b1e1e1a12f1863bd7b162d4d96ceR1-R28)
* `src/common/AFieldGroup.cpp` and `src/common/AFieldGroup.hpp`: Added `AFieldGroup` class to group multiple fields together, each with a name and description. [[1]](diffhunk://#diff-7f36d32f75c5913ca0ee9b06c956a7a8d99a34e96c3ec0730e0e845380a08a25R1-R30) [[2]](diffhunk://#diff-dc538536da07f3919776f8dbbd9e696e8a40ee5aa094aaef6fb58459351d19fbR1-R30)
* `src/common/AMeta.cpp` and `src/common/AMeta.hpp`: Added `AMeta` class to represent metadata with attributes like uniqueness, removability, and associated field groups. [[1]](diffhunk://#diff-89372bea01a72da30878c83a90b3aec2dec54b2b34656bf500cfaad97f953960R1-R43) [[2]](diffhunk://#diff-beb8b2c6dfc166850f3e51e30fcfe26b49439846e5da935f994b4c3fbcc9673dR1-R31)

### Interface Refactoring:

* [`src/common/IComponent.hpp`](diffhunk://#diff-501b2cab76de290d4794d7ed087e653e88b402eb087827fab7f1578b75271e85L67-L108): Removed deleted copy/move constructors and assignment operators from `IMeta`, `IField`, and `IFieldGroup` interfaces to simplify the code and avoid unnecessary restrictions. [[1]](diffhunk://#diff-501b2cab76de290d4794d7ed087e653e88b402eb087827fab7f1578b75271e85L67-L108) [[2]](diffhunk://#diff-501b2cab76de290d4794d7ed087e653e88b402eb087827fab7f1578b75271e85L193-L234) [[3]](diffhunk://#diff-501b2cab76de290d4794d7ed087e653e88b402eb087827fab7f1578b75271e85L289-L330)

### CMake Configuration:

* [`src/common/CMakeLists.txt`](diffhunk://#diff-623b734f767b84dff28cb49ebd68b44d56a1a0eabcc436fed6cd0ed74eb7b19fR12-R14): Updated to include the new `AMeta`, `AField`, and `AFieldGroup` source and header files in the build process. [[1]](diffhunk://#diff-623b734f767b84dff28cb49ebd68b44d56a1a0eabcc436fed6cd0ed74eb7b19fR12-R14) [[2]](diffhunk://#diff-623b734f767b84dff28cb49ebd68b44d56a1a0eabcc436fed6cd0ed74eb7b19fR23-R25)

2024-10-02 15:32 UTC, AubaneNourry requested changes
you forgot all the documentation, but otherwise it's great

2024-10-02 15:32 UTC, AubaneNourry commented on src/common/AMeta.hpp
> +//
wrong header

2024-10-02 15:50 UTC, AubaneNourry approved these changes

2024-10-02 15:51 UTC, AubaneNourry approved these changes

2024-10-06 13:09 UTC, RenardFute approved these changes
Seems fair to me 
![giphy (1)](https://github.com/user-attachments/assets/a960e3a8-f83e-41de-9e72-7b0a0a273273)

2024-10-06 15:41 UTC, merged